
name: Chris Hoyle
email: christohoyle@gmail.com
description: Chris Hoyle's blog
baseurl: "" 
url: "http://choyle.me" 

github_username:  chrishoyle
linkedin_username: christopher-hoyle


url: http://choyle.me

permalink: /:title/

version: v1.2.0

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'

sass:
  style: :expanded 

plugins:
  - jekyll-sitemap 
  - jekyll-feed 

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
