
name: Chris Hoyle
email: christohoyle@gmail.com
description: Chris Hoyle's blog
baseurl: "" 
url: "http://choyle.me" 

github_username:  chrishoyle
linkedin_username: christopher-hoyle

social-icons:
 - title: GitHub
   url: https://github.com/chrishoyle
   class: github
 - title: LinkedIn
   url: https://www.linkedin.com/in/christopher-hoyle
   class: linkedin
 - title: Facebook
   url: https://www.facebook.com/chris.hoyle.52
   class: angel
 - title: Angel-List
   url: https://angel.co/chris-hoyle-3
   class: angel

url: http://choyle.me

permalink: /:title/

version: v1.2.0

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'

sass:
  style: :expanded 

plugins:
  - jekyll-sitemap 
  - jekyll-feed 

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
