#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: Chris Hoyle
email: christohoyle@gmail.com
description: Chris Hoyle's blog
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://choyle.me" # the base hostname & protocol for your site

github_username:  chrishoyle
linkedin_username: 

google_analytics:

url: http://choyle.me



permalink: /:title/

version: v1.2.0

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'

sass:
  style: :expanded 

# Use the following plug-ins
plugins:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
